USE mydatabase;
SELECT * FROM customer LIMIT 20
#Q.1 what is the total revenue generated by male vs female customers?
SELECT gender, SUM(`purchase_amount_(usd)`)as revenue FROM customer GROUP BY gender

#Q.2 which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id,
 `purchase_amount_(usd)`
FROM customer
WHERE discount_applied = 'Yes'
AND `purchase_amount_(usd)` > (
    SELECT AVG(`purchase_amount_(usd)`)
    FROM customer
);

#Q.3 which are the top 5 products with the highest average review ratings?
SELECT item_purchased,
   ROUND(AVG(review_rating), 2) AS 
"average product rating"
FROM customer
GROUP BY item_purchased
order by `average product rating` DESC
LIMIT 5;

#Q.4 compare the average purchase amounts between standard and express shipping?
SELECT shipping_type,
AVG(`purchase_amount_(usd)`)
FROM customer
WHERE shipping_type in ('standard','express')
GROUP BY shipping_type

#Q.5 do subscribed customers spend more? compare average total revenue between subscribers and non subscribers?
SELECT subscription_status,
 COUNT(customer_id) AS 
 total_customers, 
 
ROUND(AVG(`purchase_amount_(usd)`),2) AS avg_spend, 
ROUND(SUM(`purchase_amount_(usd)`),2) AS total_revenue 
FROM customer
 GROUP BY subscription_status
 ORDER BY total_revenue DESC,
 avg_spend DESC;
 
 #Q.6 which 5 products have the highest percentage of purchase with discounts applied?
 SELECT item_purchased,
   ROUND(100 * SUM(CASE WHEN 
discount_applied = 'Yes' THEN 1 ELSE 0
 END) / COUNT(*), 2) AS discount_rate
 FROM customer
 GROUP BY item_purchased
 ORDER BY discount_rate DESC
 LIMIT 5;
 
 #Q.7 Segment customers into new, returning,and loyal based on their total number of previous purchases, and show the count of each segment.alter
 USE mydatabase;
 WITH customer_type as(
 SELECT customer_id,previous_purchases,
 CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 and 10 THEN 'returning'
    ELSE 'Loyal'
    END AS customer_segment
 FROM customer
 )
 SELECT customer_segment, COUNT(*) AS "Number of customers"
 FROM customer_type
 GROUP BY customer_segment
 
 #Q.8 what are the top 3 most purchased products within each category?
 WITH item_counts AS (
 SELECT category,
 item_purchased,
 COUNT(customer_id) AS total_orders,
 ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) as item_rank
 FROM customer
 GROUP BY category, item_purchased
 )
 SELECT item_rank,category,item_purchased,total_orders
 FROM item_counts
 WHERE item_rank <=3;
 
 #Q.9 are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 SELECT 
	subscription_status,
	COUNT(customer_id) AS repeat_buyers
 FROM customer
 WHERE previous_purchases > 5
 GROUP BY subscription_status;
 
 #Q.10 what is the revenue contribution of each age group?
 SELECT age_group,
 SUM(`purchase_amount_(usd)`) AS total_revenue
 FROM customer
 GROUP BY age_group
 ORDER BY total_revenue DESC;
 
 